const users = require('./users/users.service.js');
const companies = require('./companies/companies.service.js');
const branches = require('./branches/branches.service.js');
const departments = require('./departments/departments.service.js');
const sections = require('./sections/sections.service.js');
const roles = require('./roles/roles.service.js');
const positions = require('./positions/positions.service.js');
const profiles = require('./profiles/profiles.service.js');
const templates = require('./templates/templates.service.js');
const userAddresses = require('./userAddresses/userAddresses.service.js');
const companyAddresses = require('./companyAddresses/companyAddresses.service.js');
const companyPhones = require('./companyPhones/companyPhones.service.js');
const userPhones = require('./userPhones/userPhones.service.js');
const staffinfo = require('./staffinfo/staffinfo.service.js');
const employees = require('./employees/employees.service.js');
const superiors = require('./superiors/superiors.service.js');
const departmentAdmin = require('./departmentAdmin/departmentAdmin.service.js');
const departmentHOD = require('./departmentHOD/departmentHOD.service.js');
const departmentHOS = require('./departmentHOS/departmentHOS.service.js');
const userGuideSteps = require('./userGuideSteps/userGuideSteps.service.js');
const userGuide = require('./userGuide/userGuide.service.js');
const audits = require('./audits/audits.service.js');
const chataiEnabler = require('./chataiEnabler/chataiEnabler.service.js');
const chataiConfig = require('./chataiConfig/chataiConfig.service.js');
const chataiPrompts = require('./chataiPrompts/chataiPrompts.service.js');
const documentStorages = require('./documentStorages/documentStorages.service.js');
const fcms = require('./fcms/fcms.service.js');
const fcmQues = require('./fcmQues/fcmQues.service.js');
const fcmMessages = require('./fcmMessages/fcmMessages.service.js');
const comments = require('./comments/comments.service.js');
const helpSidebarContents = require('./helpSidebarContents/helpSidebarContents.service.js');
const loginHistories = require('./loginHistories/loginHistories.service.js');
const mailQues = require('./mailQues/mailQues.service.js');
const notifications = require('./notifications/notifications.service.js');
const profileMenu = require('./profileMenu/profileMenu.service.js');
const menuItems = require('./menuItems/menuItems.service.js');
const uploader = require('./uploader/uploader.service.js');
const userChangePassword = require('./userChangePassword/userChangePassword.service.js');
const userInvites = require('./userInvites/userInvites.service.js');
const userTrackerId = require('./userTrackerId/userTrackerId.service.js');
const permissionServices = require('./permissionServices/permissionServices.service.js');
const permissionFields = require('./permissionFields/permissionFields.service.js');
const errorLogs = require('./errorLogs/errorLogs.service.js');
const inbox = require('./inbox/inbox.service.js');
const notificationTemplates = require("./notificationTemplates/notificationTemplates.service.js");
const documentationDetails = require("./documentationDetails/documentationDetails.service.js");
// ~cb-add-require-service-name~

// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
    app.configure(users);
    app.configure(companies);
    app.configure(branches);
    app.configure(departments);
    app.configure(sections);
    app.configure(roles);
    app.configure(positions);
    app.configure(profiles);
    app.configure(templates);
    app.configure(userAddresses);
    app.configure(companyAddresses);
    app.configure(companyPhones);
    app.configure(userPhones);
    app.configure(staffinfo);
    app.configure(employees);
    app.configure(superiors);
    app.configure(departmentAdmin);
    app.configure(departmentHOD);
    app.configure(departmentHOS);
    app.configure(userGuideSteps);
    app.configure(userGuide);
    app.configure(audits);
    app.configure(chataiEnabler);
    app.configure(chataiConfig);
    app.configure(chataiPrompts);
    app.configure(documentStorages);
    app.configure(fcms);
    app.configure(fcmQues);
    app.configure(fcmMessages);
    app.configure(comments);
    app.configure(helpSidebarContents);
    app.configure(loginHistories);
    app.configure(mailQues);
    app.configure(notifications);
    app.configure(profileMenu);
    app.configure(menuItems);
    app.configure(uploader);
    app.configure(userChangePassword);
    app.configure(userInvites);
    app.configure(userTrackerId);
    app.configure(permissionServices);
    app.configure(permissionFields);
    app.configure(errorLogs);
    app.configure(inbox);
    app.configure(notificationTemplates);
     app.configure(documentationDetails);
    // ~cb-add-configure-service-name~
};
